<?php
bolt_decrypt( __FILE__ , 'QC88Gr'); return 0;
##!!!##ysfKxyseKiIwLR4gIt3+LS0ZCiwhIikw+MrHyscyMCLdBikpMiomKx4xIhkBHjEeHx4wIhkCKSwuMiIrMRkDHiAxLC8mIjAZBR4wAx4gMSwvNvjKxzIwIt0GKSkyKiYrHjEiGQEeMR4fHjAiGQIpLC4yIisxGQosISIp+MrHyscgKR4wMN0KHiYrETYtIt0iNTEiKyEw3QosISIpysc4ysfd3d3dMjAi3QUeMAMeIDEsLzb4ysc6ysc=